### ISSUE TITLE
Error barcode.go zbar.h file not found

### ISSUE THREAD

**Issue by agentelinux** [unicod3/realtime-barcode-detector#2]
Hi,

I open new issue to dev from barcode
> https://github.com/bieber/barcode/issues/1

[]s
Krishna

**Comment by agentelinux** [comment]
Sorry,
brew install zbar.

**Comment by unicod3** [comment]
Hi, 
You can also check out the links below for installing zbar:
[Linux](http://zbar.sourceforge.net/download.html)
[MacOs](http://macappstore.org/zbar/)
[Windows](http://zbar.sourceforge.net/download.html)
